### ISSUE TITLE
Capítulo Explicativo 50 páginas(gráficos e tabelas)

### ISSUE THREAD

**Issue by luisfcosta2015** [luisfcosta2015/PLUGsPLAY#23]
5 páginas sobre cada tema;
Engajamento/pertencimento;
Engenharia de Software;
Jogo;
The kernel as the rules of the game;

**Comment by mayareyesricon** [comment]
Elaborar a sessão Proposta inicial para ramifica;áo de acordo co os coment[arios no texto
